sudo: required
language: python
python: "3.6"

before_install:
  - cd ${TRAVIS_BUILD_DIR}

install:
  - pip install google-compute-engine # see https://github.com/tendenci/tendenci/issues/539
  - pip3 install -r requirements.txt
  - pip3 install tox

script:
  - tox
